version: '3.9'

services:
  search-postgres:
    image: postgres:13.0
    container_name: search-postgres
    environment:
      POSTGRES_DB: search_service
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"  # ActiveMQ broker port for JMS clients
      - "8161:8161"    # Web console port
    environment:
      ACTIVEMQ_ADMIN_LOGIN: ${ACTIVE_MQ_USER}
      ACTIVEMQ_ADMIN_PASSWORD: ${ACTIVE_MQ_PASSWORD}
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 1024
    volumes:
      - activemq-data:/var/activemq/data

#  product-service-app:
#    image: search-service-app-image
#    container_name: search-service-app
#    depends_on:
#      - search-postgres
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/search_service
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: admin
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    networks:
#      - spring-boot-postgres-network

volumes:
  postgres_data:
  activemq-data:

networks:
  spring-boot-postgres-network:
