version: '3.9'

services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"  # ActiveMQ broker port for JMS clients
      - "8161:8161"    # Web console port
    environment:
      ACTIVEMQ_ADMIN_LOGIN: ${ACTIVE_MQ_USER}
      ACTIVEMQ_ADMIN_PASSWORD: ${ACTIVE_MQ_PASSWORD}
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 1024
    volumes:
      - activemq-data:/var/activemq/data

volumes:
  activemq-data:

networks:
  spring-boot-postgres-network:
